#!/bin/bash
CWD="$(pwd)"
cd $(dirname ${0})
cd ..
START_DIR=$(pwd)
if [ -d ${START_DIR}/profiles ]; then
  cd ${START_DIR}/profiles
  if [ $(find * -name .vault.dat -type f 2>/dev/null | wc -l) -gt 0 ]; then
    for D in $(find * -name .vault.dat -type f 2>/dev/null) ; do
      echo "$(dirname ${D})"
    done
  fi
fi
